spring:
  application:
    name: with

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:postgres}
    driver-class-name: org.postgresql.Driver

    jpa:
      database-platform: org.hibernate.dialect.PostgresSQLDialect
      hibernate:
        ddl-auto: validate
      show-sql: true

  logging:
    level:
      root: INFO


vacancy:
  pageSize: 25


management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, loggers'
  metrics:
    export:
      prometheus:
        enabled: true