spring:
  application:
    name: with
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ''
            clientSecret: ''
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          github:
            clientId: ''
            clientSecret: ''
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

  datasource:
    url: jdbc:postgresql://localhost:5432/databasenEW
    username: rushglow
    password: password1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

  cloud:
    vault:
      uri: ${VAULT_SERVER}
      connection-timeout: 5000
      read-timeout: 15000
      authentication: TOKEN
      token: ${VAULT_TOKEN}
      kv:
        application-name: with
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: with

  config:
    import: vault://

vacancy:
  pageSize: 25

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, loggers'
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    oauth:
      client-id: ${spring.security.oauth2.client.registration.google.client-id}
      client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
      scopes: email, profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html

app:
  auth:
    tokenSecret: ''
    duration: 15m
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:8080/oauth2/callback/
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect