server:
  servlet:
    context-path: /api/v1/

spring:
  application:
    name: with

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:postgrespw}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    show-sql: true

vacancy:
  pageSize: 25

jwt:
  secret: QNsgkaQlOLZcgaQL0IX5XHK84M+g7V2sDlVZDdAeR4s=
  duration: 15m

management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 'prometheus, health, loggers'
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
