openapi: 3.0.0
info:
  title: API of service WEB3.WITH
  description: Operations of service
  version: 1.0.0
servers:
  - url: /main
paths:
  /vacancies:
    get:
      summary: Получение списка вакансий
      operationId: getVacancies
      tags:
        - Vacancies
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VacanciesRs'
components:
  schemas:
    VacanciesRs:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string